### ISSUE TITLE
Переключение свитча не запускает цикл

### ISSUE THREAD

**Issue by seele402** [JigiDo/Heute#15]
При нажатии на свитч, он переходит в состояние On, но не исполняет привязанный код.
Вероятно, проблема в этой строке
https://github.com/JigiDo/Heute/blob/fd025f2bf5b06fb9db589cd89492758cb08478c0/Heute/MainWindow.xaml.cs#L35

**Comment by moetelo** [comment]
А что у тебя должно происходить в этом блоке по-твоему, Никит?

**Comment by seele402** [comment]
https://github.com/JigiDo/Heute/blob/fd025f2bf5b06fb9db589cd89492758cb08478c0/Heute/MainWindow.xaml.cs#L37-L55

**Comment by moetelo** [comment]
@JigiDo 
Ну. `Hour = Minute = Second = 0`.
Если `DateTime.Now.Hour == 0`, `DateTime.Now.Minute == 0` и `DateTime.Now.Second == 0`, то выполняется код под **if**. 
Или системное время на 23:59 менял?

**Comment by moetelo** [comment]
Ты ставил там брейкпоинт какой-нибудь, ну или хотя бы MessageBox? Поток точно не попадает в этот блок?

**Comment by seele402** [comment]
С первым ясно, а со вторым ты недопонял. При нажатии на свитч просто не запускается ничего после  строки в шапке, я уже пробовал и без циклов и ифов заставлять программу по нажатию отсылать сообщение, но активация свитча просто ни к чему не приводит.

**Comment by seele402** [comment]
Основная проблема в том, что свитч в отдельный класс переносил Никита и как он реализовал это я не понимаю, потому и не знаю, что не так в коде.
